// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFZjgj1QNR4-ve5DgFNoLgTlS8gp8CxTE',
    appId: '1:669775987132:web:5654bee82c5dde93d8abb9',
    messagingSenderId: '669775987132',
    projectId: 'rentalappexercise',
    authDomain: 'rentalappexercise.firebaseapp.com',
    storageBucket: 'rentalappexercise.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXo_KiUE2ArfgajGEmkAbJSOEwep6LjFI',
    appId: '1:669775987132:android:b17505ad479ae678d8abb9',
    messagingSenderId: '669775987132',
    projectId: 'rentalappexercise',
    storageBucket: 'rentalappexercise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf6q_KCTGQL-xoW6GcA55OcHegubd3tGU',
    appId: '1:669775987132:ios:e259f9252e78b898d8abb9',
    messagingSenderId: '669775987132',
    projectId: 'rentalappexercise',
    storageBucket: 'rentalappexercise.firebasestorage.app',
    iosBundleId: 'com.example.balirentalProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf6q_KCTGQL-xoW6GcA55OcHegubd3tGU',
    appId: '1:669775987132:ios:e259f9252e78b898d8abb9',
    messagingSenderId: '669775987132',
    projectId: 'rentalappexercise',
    storageBucket: 'rentalappexercise.firebasestorage.app',
    iosBundleId: 'com.example.balirentalProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFZjgj1QNR4-ve5DgFNoLgTlS8gp8CxTE',
    appId: '1:669775987132:web:2b4f971f550491e4d8abb9',
    messagingSenderId: '669775987132',
    projectId: 'rentalappexercise',
    authDomain: 'rentalappexercise.firebaseapp.com',
    storageBucket: 'rentalappexercise.firebasestorage.app',
  );

}